//
//  CharacterListPresenter.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListPresentationLogic {
    func presentCharacters(response: CharacterList.FetchCharacters.Response)
}

class CharacterListPresenter: CharacterListPresentationLogic {
    
    weak var viewController: CharacterListDisplayLogic?
    
    func presentCharacters(response: CharacterList.FetchCharacters.Response) {
        let characterViewModels = response.characters.map { character in
            return CharacterList.FetchCharacters.ViewModel.CharacterViewModel(
                id: character.id,
                name: character.name,
                species: character.species,
                status: character.status,
                imageUrl: character.image
            )
        }
        
        let errorMessage = response.error?.localizedDescription
        
        let viewModel = CharacterList.FetchCharacters.ViewModel(
            characters: characterViewModels,
            errorMessage: errorMessage
        )
        
        viewController?.displayCharacters(viewModel: viewModel)
    }
}
