//
//  CharacterListViewController.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListDisplayLogic: AnyObject {
    func displayCharacters(viewModel: CharacterList.FetchCharacters.ViewModel)
}

class CharacterListViewController: UIViewController, CharacterListDisplayLogic {
    
    private var interactor: CharacterListBusinessLogic?
    private var router: (CharacterListRoutingLogic & CharacterListDataPassing)?
    
    private let tableView = UITableView()
    private var characters: [CharacterList.FetchCharacters.ViewModel.CharacterViewModel] = []
    
    // MARK: - Lifecycle
    init(interactor: CharacterListBusinessLogic, router: (CharacterListRoutingLogic & CharacterListDataPassing)) {
        super.init(nibName: nil, bundle: nil)
        self.interactor = interactor
        self.router = router
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Rick and Morty Characters"
        setupTableView()
        fetchCharacters()
    }
    
    private func setupTableView() {
        view.addSubview(tableView)
        tableView.translatesAutoresizingMaskIntoConstraints = false
        tableView.bindFrameToSuperview()
        tableView.separatorStyle = .none
        
        tableView.register(CharacterCell.self, forCellReuseIdentifier: CharacterCell.reuseIdentifier)
        tableView.delegate = self
        tableView.dataSource = self
    }
    
    private func fetchCharacters() {
        interactor?.fetchCharacters(request: CharacterList.FetchCharacters.Request(page: 1))
    }
    
    // MARK: - Display logic
    func displayCharacters(viewModel: CharacterList.FetchCharacters.ViewModel) {
        DispatchQueue.main.async { [weak self] in
            self?.characters = viewModel.characters
            self?.tableView.reloadData()
        }
    }
}

// MARK: - UITableViewDataSource & UITableViewDelegate
extension CharacterListViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return characters.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: CharacterCell.reuseIdentifier, for: indexPath) as? CharacterCell else {
            return UITableViewCell()
        }
        
        let character = characters[indexPath.row]
        cell.configure(with: character)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        
        let characterID = characters[indexPath.row].id
        router?.routeToCharacterDetail(characterID: characterID)
    }
}
