//
//  CharacterListModels.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterList {
    
    enum FetchCharacters {
        struct Request {
            let page: Int
        }
        
        struct Response {
            let characters: [Character]
            let error: Error?
        }
        
        struct ViewModel {
            let characters: [CharacterViewModel]
            let errorMessage: String?
            
            struct CharacterViewModel {
                let id: Int
                let name: String
                let species: String
                let status: String
                let imageUrl: String
            }
        }
    }
    
    enum SelectCharacter {
        struct Request {
            let id: Int
        }
        
        struct Response {
            let id: Int
        }
        
        struct ViewModel {
            let id: Int
        }
    }
}
