//
//  CharacterDetailsRouter.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharacterDetailsRoutingLogic { }

protocol CharacterDetailsDataPassing {
    var dataStore: CharacterDetailsDataStore? { get }
}

class CharacterDetailsRouter: NSObject, CharacterDetailsRoutingLogic, CharacterDetailsDataPassing {
    weak var viewController: CharacterDetailsViewController?
    var dataStore: CharacterDetailsDataStore?
}
