//
//  CharacterDetailsWorker.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class CharacterDetailsWorker {
    private let repository: CharacterRepositoryProtocol
    
    init(networkService: NetworkServiceProtocol, persistenceService: CharacterPersistenceService) {
        repository = CharacterRepository(networkService: networkService, persistenceService: persistenceService)
    }
    
    init(repository: CharacterRepositoryProtocol) {
        self.repository = repository
    }
    
    func fetchCharacterDetails(characterID: Int, completion: @escaping (Character?) -> Void) {
        repository.getCharacter(id: characterID) { result in
            switch result {
            case .success(let character):
                completion(character)
            case .failure:
                completion(nil)
            }
        }
    }
}
