//
//  CharacterDetailsWorker.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterDetailsWorker {
    var networkService: NetworkServiceProtocol
    
    init(networkService: NetworkServiceProtocol) {
        self.networkService = networkService
    }
    
    func fetchCharacterDetails(characterID: Int, completion: @escaping (Character?) -> Void) {
        networkService.fetchCharacter(characterID: characterID) { result in
            switch result {
            case .success(let response):
                completion(response)
            case .failure(let error):
                completion(nil)
            }
        }
    }
}
