//
//  CharacterDetailsModels.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterDetails {
    
    enum FetchCharacterDetails {
        struct Request {
            let id: Int
        }
        
        struct Response {
            let character: Character?
        }
        
        struct ViewModel {
            let name: String
            let status: String
            let species: String
            let gender: String
            let origin: String
            let location: String
            let imageURL: String
            
            var statusText: String { "Status: \(status)" }
            var speciesText: String { "Species: \(species)" }
            var genderText: String { "Gender: \(gender)" }
            var originText: String { "Origin: \(origin)" }
            var locationText: String { "Location: \(location)" }
        }
    }
}
