//
//  CharacterDetailsInteractor.swift
//  RickAndMorty
//
//  Created by  Oleksandra on 07.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic: AnyObject {
    func fetchCharacterDetails()
}

protocol CharacterDetailsDataStore {
    var characterID: Int { get set }
}

class CharacterDetailsInteractor: CharacterDetailsBusinessLogic, CharacterDetailsDataStore {
    
    var presenter: CharacterDetailsPresentationLogic?
    var worker: CharacterDetailsWorker?
    var characterID: Int
    
    init(networkService: NetworkServiceProtocol, persistenceService: CharacterPersistenceService, characterID: Int) {
        worker = CharacterDetailsWorker(networkService: networkService,
                                        persistenceService: persistenceService)
        self.characterID = characterID
    }
    
    func fetchCharacterDetails() {
        worker?.fetchCharacterDetails(characterID: characterID) { [weak self] character in
            let response = CharacterDetails.FetchCharacterDetails.Response(character: character)
            self?.presenter?.presentCharacterDetails(response: response)
        }
    }
}
